name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        java:
          - 17
          - 21
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            11
            ${{ matrix.java }}
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - uses: codecov/codecov-action@v5
        with:
          name: jacoco-${{ matrix.java }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
