name: CD

on:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Publish package to the Maven Central Repository
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
        if: env.SONATYPE_TOKEN != null
        run: |
          printf "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > $RUNNER_TEMP/secring.gpg
          chmod +x ./gradlew
          ./gradlew -Psigning.keyId=${{ secrets.GPG_KEYID }} \
          -Psigning.password=${{ secrets.GPG_PASSPHRASE }} \
          -Psigning.secretKeyRingFile=$RUNNER_TEMP/secring.gpg \
          publish
