name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        java:
          - 8
          - 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - uses: codecov/codecov-action@v1
        with:
          name: unittests-${{ matrix.java }}
          fail_ci_if_error: true
